/**
 * 自動生成。手で編集しない（`npm run gen:content` で作り直す）。
 *
 * ことばの 正（content/vocab/*.json）の うち、英語の 意味を 持つ 語を
 * 語彙メモの かたちに 焼いた もの（scripts/generate_glossary.mjs）。
 * 語を 直したい ときは **正の JSON を 直す**。ここを 直しても 次の 生成で 消える。
 */

import type { GlossaryEntry } from "./glossary";

export const GENERATED_GLOSSARY: readonly GlossaryEntry[] = [
  {"term":"予定","kanji":"予定","reading":"よてい","meaning":"「いつ 何を するか」を 先に きめた もの","englishTerm":"a plan","englishMeaning":"what you decided to do, and when"},
  {"term":"失敗","kanji":"失敗","reading":"しっぱい","meaning":"やって みたが、思った とおりに ならない こと","englishTerm":"a slip-up","englishMeaning":"when something does not go the way you wanted"},
  {"term":"チーム","kanji":null,"reading":"ちーむ","meaning":"おなじ しごとを いっしょに する 人たち","englishTerm":"team","englishMeaning":"the people you work together with"},
  {"term":"プログラム","kanji":null,"reading":"ぷろぐらむ","meaning":"パソコンに 「こう うごいて」と 教える ことば","englishTerm":"program, code","englishMeaning":"the instructions that tell a computer what to do"},
  {"term":"技術","kanji":"技術","reading":"ぎじゅつ","meaning":"つくる ための ほうほう","englishTerm":"technology","englishMeaning":"the methods and skills used to build things"},
  {"term":"道具","kanji":"道具","reading":"どうぐ","meaning":"しごとで 手に もって つかう もの","englishTerm":"a tool","englishMeaning":"a thing you hold and use to do a job"},
  {"term":"組","kanji":"組","reading":"ぐみ","meaning":"おなじ タイプの なかまの グループ","englishTerm":"group","englishMeaning":"the four families of types in this app"},
  {"term":"仲間","kanji":"仲間","reading":"なかま","meaning":"いっしょに べんきょうや しごとを する 友だち","englishTerm":"teammate","englishMeaning":"someone you study or work together with"},
  {"term":"手順","kanji":"手順","reading":"てじゅん","meaning":"しごとの じゅんばん","englishTerm":"steps","englishMeaning":"the order you do a job in"},
  {"term":"運用","kanji":"運用","reading":"うんよう","meaning":"つくった システムを まいにち うごかしつづける しごと","englishTerm":"operations","englishMeaning":"keeping a finished system running every day"},
  {"term":"対応","kanji":"対応","reading":"たいおう","meaning":"もんだいが 出た とき、それを なおす しごと","englishTerm":"handling","englishMeaning":"dealing with a problem when one comes up"},
  {"term":"仕組み","kanji":"仕組み","reading":"しくみ","meaning":"どう うごいて いるか。なかの つくり","englishTerm":"mechanism","englishMeaning":"how something works inside"},
  {"term":"設計","kanji":"設計","reading":"せっけい","meaning":"つくる 前に、どう つくるかを きめる こと","englishTerm":"design","englishMeaning":"deciding how to build it before you build it"},
  {"term":"提案","kanji":"提案","reading":"ていあん","meaning":"「こう しませんか」と 言う こと","englishTerm":"proposal","englishMeaning":"saying 「let's do it this way」"},
  {"term":"伝える","kanji":"伝える","reading":"つたえる","meaning":"あいてに 話して、わかって もらう こと","englishTerm":"to tell someone","englishMeaning":"to say it so the other person understands"},
  {"term":"気持ち","kanji":"気持ち","reading":"きもち","meaning":"うれしい・かなしい など、その とき 思って いる こと","englishTerm":"feelings","englishMeaning":"how someone feels inside at that moment"},
  {"term":"理由","kanji":"理由","reading":"りゆう","meaning":"「どうして そう するのか」の こたえ","englishTerm":"the reason","englishMeaning":"why you do it that way"},
  {"term":"説明","kanji":"説明","reading":"せつめい","meaning":"わからない 人に、わかるように 話す こと","englishTerm":"explanation","englishMeaning":"telling someone so that they understand"},
  {"term":"大切","kanji":"大切","reading":"たいせつ","meaning":"とても だいじで、なくしたく ない こと","englishTerm":"important","englishMeaning":"something that matters a lot to you"},
  {"term":"使い方","kanji":"使い方","reading":"つかいかた","meaning":"その ものを どう つかうか","englishTerm":"how to use it","englishMeaning":"the way you are supposed to use something"},
  {"term":"考え方","kanji":"考え方","reading":"かんがえかた","meaning":"ものごとを どう 見て、どう きめるか","englishTerm":"way of thinking","englishMeaning":"how a person looks at things and decides"},
  {"term":"考え","kanji":"考え","reading":"かんがえ","meaning":"あたまの 中で 思った こと","englishTerm":"an idea","englishMeaning":"what you have in mind"},
  {"term":"目標","kanji":"目標","reading":"もくひょう","meaning":"「ここまで やる」と きめた こと","englishTerm":"goal","englishMeaning":"what you are trying to reach"},
  {"term":"締め切り","kanji":"締め切り","reading":"しめきり","meaning":"「この 日までに おわらせる」と きめた 日","englishTerm":"deadline","englishMeaning":"the day the work has to be finished by"},
  {"term":"段取り","kanji":"段取り","reading":"だんどり","meaning":"はじめる 前に、しごとの じゅんばんを きめて おく こと","englishTerm":"planning ahead","englishMeaning":"setting up the order of work before starting"},
  {"term":"仕上げ","kanji":"仕上げ","reading":"しあげ","meaning":"さいごに きれいに して、おわらせる こと","englishTerm":"finishing touches","englishMeaning":"the last pass that makes it clean"},
  {"term":"結果","kanji":"結果","reading":"けっか","meaning":"やった あとに、どう なるか","englishTerm":"outcome","englishMeaning":"how it turns out in the end"},
  {"term":"ものづくり","kanji":null,"reading":"ものづくり","meaning":"アプリや せいひんを 作る しごと","englishTerm":"making things","englishMeaning":"building apps and products"},
  {"term":"おもいやり","kanji":null,"reading":"おもいやり","meaning":"あいての きもちを かんがえる こと","englishTerm":"considerateness","englishMeaning":"thinking about how the other person feels"},
  {"term":"おせわ","kanji":null,"reading":"おせわ","meaning":"人を てつだう こと・気を つかう こと","englishTerm":"looking after people","englishMeaning":"helping them and paying attention to them"},
  {"term":"おうえん","kanji":null,"reading":"おうえん","meaning":"「がんばって」と 言って、元気に する こと","englishTerm":"cheering on","englishMeaning":"saying 「you can do it」"},
  {"term":"わくわく","kanji":null,"reading":"わくわく","meaning":"たのしみで、はやく やりたいと 思う きもち","englishTerm":"excited","englishMeaning":"the feeling of looking forward to something"},
  {"term":"トラブル","kanji":null,"reading":"とらぶる","meaning":"システムが うまく うごかない こと","englishTerm":"trouble","englishMeaning":"when a system stops working properly"},
  {"term":"スマホ","kanji":null,"reading":"すまほ","meaning":"スマートフォン","englishTerm":"smartphone","englishMeaning":"a phone you can use like a small computer"},
  {"term":"よそう","kanji":null,"reading":"よそう","meaning":"これから どう なるかを、先に かんがえる こと","englishTerm":"predicting","englishMeaning":"thinking ahead about what will happen"},
  {"term":"もりあげ","kanji":null,"reading":"もりあげ","meaning":"みんなを 楽しく、元気に する こと","englishTerm":"lifting the mood","englishMeaning":"making everyone lively and cheerful"},
  {"term":"性格","kanji":"性格","reading":"せいかく","meaning":"その 人の、いつもの かんがえかたや やりかた","englishTerm":"personality","englishMeaning":"the way a person usually thinks and acts"},
  {"term":"診断","kanji":"診断","reading":"しんだん","meaning":"しつもんに 答えて、じぶんの ことを しらべる こと","englishTerm":"check-up","englishMeaning":"answering questions to find out about yourself"},
  {"term":"意見","kanji":"意見","reading":"いけん","meaning":"「そう 思う」と じぶんが かんがえた こと","englishTerm":"opinion","englishMeaning":"what you think about something"},
  {"term":"一生懸命","kanji":"一生懸命","reading":"いっしょうけんめい","meaning":"力を ぜんぶ 出して やる こと","englishTerm":"with all your effort","englishMeaning":"putting all your energy into what you do"},
  {"term":"安心","kanji":"安心","reading":"あんしん","meaning":"しんぱいが なくなって、きもちが 楽に なる こと","englishTerm":"relief","englishMeaning":"the calm you feel when you stop worrying"},
  {"term":"途中","kanji":"途中","reading":"とちゅう","meaning":"はじめてから おわるまでの あいだ","englishTerm":"partway","englishMeaning":"after starting but before finishing"},
  {"term":"試す","kanji":"試す","reading":"ためす","meaning":"できるか どうか、いちど やって みる こと","englishTerm":"to try","englishMeaning":"doing it once to see what happens"},
  {"term":"例","kanji":"例","reading":"れい","meaning":"「たとえば こういう こと」と 見せる もの","englishTerm":"example","englishMeaning":"something shown to explain what you mean"},
  {"term":"部屋","kanji":"部屋","reading":"へや","meaning":"いえや たてものの 中の、ドアで しきられた ところ","englishTerm":"room","englishMeaning":"a space inside a building with walls and a door"},
  {"term":"机","kanji":"机","reading":"つくえ","meaning":"パソコンや ノートを おいて、べんきょうや しごとを する もの","englishTerm":"desk","englishMeaning":"the table you study or work at"},
  {"term":"紙","kanji":"紙","reading":"かみ","meaning":"書くための、うすくて しろい もの","englishTerm":"paper","englishMeaning":"a thin white sheet you write on"},
  {"term":"頭","kanji":"頭","reading":"あたま","meaning":"ものを 考える ところ。ぼうしを かぶる ところ","englishTerm":"head","englishMeaning":"the part of your body you think with"},
  {"term":"家","kanji":"家","reading":"いえ","meaning":"じぶんが すんで いる ところ","englishTerm":"home","englishMeaning":"the place where you live"},
  {"term":"一日","kanji":"一日","reading":"いちにち","meaning":"あさから よるまで。24時間の こと","englishTerm":"one day","englishMeaning":"from morning until night"},
  {"term":"本当","kanji":"本当","reading":"ほんとう","meaning":"うそでは ない こと。じっさいに あった こと","englishTerm":"real, true","englishMeaning":"not a lie; something that really happened"},
  {"term":"早め","kanji":"早め","reading":"はやめ","meaning":"きめた 時間より 前に する こと","englishTerm":"a little early","englishMeaning":"doing it before the time you were given"},
  {"term":"質問","kanji":"質問","reading":"しつもん","meaning":"わからない ことを、人に たずねる こと","englishTerm":"question","englishMeaning":"asking someone about something you do not know"},
  {"term":"元気","kanji":"元気","reading":"げんき","meaning":"体や 気持ちに 力が ある こと","englishTerm":"energy, cheerful","englishMeaning":"feeling strong and well in body and mind"},
  {"term":"やり方","kanji":"やり方","reading":"やりかた","meaning":"どう すれば できるか、という こと","englishTerm":"way of doing","englishMeaning":"the steps and style you use to do something"},
  {"term":"アプリ","kanji":null,"reading":"あぷり","meaning":"スマホや パソコンの 中で うごく もの。ちずや ゲームなど","englishTerm":"app","englishMeaning":"a program you use on a phone or computer"},
  {"term":"アイデア","kanji":null,"reading":"あいであ","meaning":"「こう したら いいかも」と 思いついた 考え","englishTerm":"idea","englishMeaning":"a new thought about what you could do"},
];
