/**
 * 自動生成。手で編集しない（`npm run gen:content` で作り直す）。
 *
 * ことばの 正（content/vocab/*.json）の うち、英語の 意味を 持つ 語を
 * 語彙メモの かたちに 焼いた もの（scripts/generate_glossary.mjs）。
 * 語を 直したい ときは **正の JSON を 直す**。ここを 直しても 次の 生成で 消える。
 */

import type { GlossaryEntry } from "./glossary";

export const GENERATED_GLOSSARY: readonly GlossaryEntry[] = [
  {"term":"予定","kanji":"予定","reading":"よてい","meaning":"「いつ 何を するか」を 先に きめた もの","englishTerm":"a plan","englishMeaning":"what you decided to do, and when"},
  {"term":"失敗","kanji":"失敗","reading":"しっぱい","meaning":"やって みたが、思った とおりに ならない こと","englishTerm":"a slip-up","englishMeaning":"when something does not go the way you wanted"},
  {"term":"チーム","kanji":null,"reading":"ちーむ","meaning":"おなじ しごとを いっしょに する 人たち","englishTerm":"team","englishMeaning":"the people you work together with"},
  {"term":"プログラム","kanji":null,"reading":"ぷろぐらむ","meaning":"パソコンに 「こう うごいて」と 教える ことば","englishTerm":"program, code","englishMeaning":"the instructions that tell a computer what to do"},
  {"term":"技術","kanji":"技術","reading":"ぎじゅつ","meaning":"つくる ための ほうほう","englishTerm":"technology","englishMeaning":"the methods and skills used to build things"},
  {"term":"道具","kanji":"道具","reading":"どうぐ","meaning":"しごとで 手に もって つかう もの","englishTerm":"a tool","englishMeaning":"a thing you hold and use to do a job"},
  {"term":"画面","kanji":"画面","reading":"がめん","meaning":"パソコンや スマホの、字や 絵が 見える ところです。","englishTerm":"Screen / Display","englishMeaning":"the part of a computer or phone that shows things"},
  {"term":"丁寧","kanji":"丁寧","reading":"ていねい","meaning":"急がないで、こまかい ところまで 気を つける ようすです。","englishTerm":"Polite / Careful","englishMeaning":"doing something slowly and with care"},
  {"term":"得意","kanji":"得意","reading":"とくい","meaning":"ほかの ことより、うまく できる ことです。","englishTerm":"Strong point","englishMeaning":"something you can do well"},
  {"term":"組","kanji":"組","reading":"ぐみ","meaning":"おなじ タイプの なかまの グループ","englishTerm":"group","englishMeaning":"the four families of types in this app"},
  {"term":"仲間","kanji":"仲間","reading":"なかま","meaning":"いっしょに べんきょうや しごとを する 友だち","englishTerm":"teammate","englishMeaning":"someone you study or work together with"},
  {"term":"手順","kanji":"手順","reading":"てじゅん","meaning":"しごとの じゅんばん","englishTerm":"steps","englishMeaning":"the order you do a job in"},
  {"term":"運用","kanji":"運用","reading":"うんよう","meaning":"つくった システムを まいにち うごかしつづける しごと","englishTerm":"operations","englishMeaning":"keeping a finished system running every day"},
  {"term":"対応","kanji":"対応","reading":"たいおう","meaning":"もんだいが 出た とき、それを なおす しごと","englishTerm":"handling","englishMeaning":"dealing with a problem when one comes up"},
  {"term":"仕組み","kanji":"仕組み","reading":"しくみ","meaning":"どう うごいて いるか。なかの つくり","englishTerm":"mechanism","englishMeaning":"how something works inside"},
  {"term":"設計","kanji":"設計","reading":"せっけい","meaning":"つくる 前に、どう つくるかを きめる こと","englishTerm":"design","englishMeaning":"deciding how to build it before you build it"},
  {"term":"提案","kanji":"提案","reading":"ていあん","meaning":"「こう しませんか」と 言う こと","englishTerm":"proposal","englishMeaning":"saying 「let's do it this way」"},
  {"term":"伝える","kanji":"伝える","reading":"つたえる","meaning":"あいてに 話して、わかって もらう こと","englishTerm":"to tell someone","englishMeaning":"to say it so the other person understands"},
  {"term":"気持ち","kanji":"気持ち","reading":"きもち","meaning":"うれしい・かなしい など、その とき 思って いる こと","englishTerm":"feelings","englishMeaning":"how someone feels inside at that moment"},
  {"term":"理由","kanji":"理由","reading":"りゆう","meaning":"「どうして そう するのか」の こたえ","englishTerm":"the reason","englishMeaning":"why you do it that way"},
  {"term":"説明","kanji":"説明","reading":"せつめい","meaning":"わからない 人に、わかるように 話す こと","englishTerm":"explanation","englishMeaning":"telling someone so that they understand"},
  {"term":"大切","kanji":"大切","reading":"たいせつ","meaning":"とても だいじで、なくしたく ない こと","englishTerm":"important","englishMeaning":"something that matters a lot to you"},
  {"term":"使い方","kanji":"使い方","reading":"つかいかた","meaning":"その ものを どう つかうか","englishTerm":"how to use it","englishMeaning":"the way you are supposed to use something"},
  {"term":"考え方","kanji":"考え方","reading":"かんがえかた","meaning":"ものごとを どう 見て、どう きめるか","englishTerm":"way of thinking","englishMeaning":"how a person looks at things and decides"},
  {"term":"考え","kanji":"考え","reading":"かんがえ","meaning":"あたまの 中で 思った こと","englishTerm":"an idea","englishMeaning":"what you have in mind"},
  {"term":"目標","kanji":"目標","reading":"もくひょう","meaning":"「ここまで やる」と きめた こと","englishTerm":"goal","englishMeaning":"what you are trying to reach"},
  {"term":"締め切り","kanji":"締め切り","reading":"しめきり","meaning":"「この 日までに おわらせる」と きめた 日","englishTerm":"deadline","englishMeaning":"the day the work has to be finished by"},
  {"term":"段取り","kanji":"段取り","reading":"だんどり","meaning":"はじめる 前に、しごとの じゅんばんを きめて おく こと","englishTerm":"planning ahead","englishMeaning":"setting up the order of work before starting"},
  {"term":"仕上げ","kanji":"仕上げ","reading":"しあげ","meaning":"さいごに きれいに して、おわらせる こと","englishTerm":"finishing touches","englishMeaning":"the last pass that makes it clean"},
  {"term":"結果","kanji":"結果","reading":"けっか","meaning":"やった あとに、どう なるか","englishTerm":"outcome","englishMeaning":"how it turns out in the end"},
  {"term":"ものづくり","kanji":null,"reading":"ものづくり","meaning":"アプリや せいひんを 作る しごと","englishTerm":"making things","englishMeaning":"building apps and products"},
  {"term":"おもいやり","kanji":null,"reading":"おもいやり","meaning":"あいての きもちを かんがえる こと","englishTerm":"considerateness","englishMeaning":"thinking about how the other person feels"},
  {"term":"おせわ","kanji":null,"reading":"おせわ","meaning":"人を てつだう こと・気を つかう こと","englishTerm":"looking after people","englishMeaning":"helping them and paying attention to them"},
  {"term":"おうえん","kanji":null,"reading":"おうえん","meaning":"「がんばって」と 言って、元気に する こと","englishTerm":"cheering on","englishMeaning":"saying 「you can do it」"},
  {"term":"わくわく","kanji":null,"reading":"わくわく","meaning":"たのしみで、はやく やりたいと 思う きもち","englishTerm":"excited","englishMeaning":"the feeling of looking forward to something"},
  {"term":"トラブル","kanji":null,"reading":"とらぶる","meaning":"システムが うまく うごかない こと","englishTerm":"trouble","englishMeaning":"when a system stops working properly"},
  {"term":"スマホ","kanji":null,"reading":"すまほ","meaning":"スマートフォン","englishTerm":"smartphone","englishMeaning":"a phone you can use like a small computer"},
  {"term":"よそう","kanji":null,"reading":"よそう","meaning":"これから どう なるかを、先に かんがえる こと","englishTerm":"predicting","englishMeaning":"thinking ahead about what will happen"},
  {"term":"もりあげ","kanji":null,"reading":"もりあげ","meaning":"みんなを 楽しく、元気に する こと","englishTerm":"lifting the mood","englishMeaning":"making everyone lively and cheerful"},
  {"term":"性格","kanji":"性格","reading":"せいかく","meaning":"その 人の、いつもの かんがえかたや やりかた","englishTerm":"personality","englishMeaning":"the way a person usually thinks and acts"},
  {"term":"診断","kanji":"診断","reading":"しんだん","meaning":"しつもんに 答えて、じぶんの ことを しらべる こと","englishTerm":"check-up","englishMeaning":"answering questions to find out about yourself"},
  {"term":"タイプ","kanji":null,"reading":"たいぷ","meaning":"にた ところが ある 人の グループ","englishTerm":"type","englishMeaning":"a group of people who are alike"},
  {"term":"参考","kanji":"参考","reading":"さんこう","meaning":"つぎに どう するかを きめる とき、たすけに する こと","englishTerm":"reference","englishMeaning":"something you look at to help you decide"},
  {"term":"意見","kanji":"意見","reading":"いけん","meaning":"「そう 思う」と じぶんが かんがえた こと","englishTerm":"opinion","englishMeaning":"what you think about something"},
  {"term":"一生懸命","kanji":"一生懸命","reading":"いっしょうけんめい","meaning":"力を ぜんぶ 出して やる こと","englishTerm":"with all your effort","englishMeaning":"putting all your energy into what you do"},
  {"term":"安心","kanji":"安心","reading":"あんしん","meaning":"しんぱいが なくなって、きもちが 楽に なる こと","englishTerm":"relief","englishMeaning":"the calm you feel when you stop worrying"},
  {"term":"途中","kanji":"途中","reading":"とちゅう","meaning":"はじめてから おわるまでの あいだ","englishTerm":"partway","englishMeaning":"after starting but before finishing"},
  {"term":"試す","kanji":"試す","reading":"ためす","meaning":"できるか どうか、いちど やって みる こと","englishTerm":"to try","englishMeaning":"doing it once to see what happens"},
  {"term":"例","kanji":"例","reading":"れい","meaning":"「たとえば こういう こと」と 見せる もの","englishTerm":"example","englishMeaning":"something shown to explain what you mean"},
  {"term":"部屋","kanji":"部屋","reading":"へや","meaning":"いえや たてものの 中の、ドアで しきられた ところ","englishTerm":"room","englishMeaning":"a space inside a building with walls and a door"},
  {"term":"机","kanji":"机","reading":"つくえ","meaning":"パソコンや ノートを おいて、べんきょうや しごとを する もの","englishTerm":"desk","englishMeaning":"the table you study or work at"},
  {"term":"紙","kanji":"紙","reading":"かみ","meaning":"書くための、うすくて しろい もの","englishTerm":"paper","englishMeaning":"a thin white sheet you write on"},
  {"term":"頭","kanji":"頭","reading":"あたま","meaning":"ものを 考える ところ。ぼうしを かぶる ところ","englishTerm":"head","englishMeaning":"the part of your body you think with"},
  {"term":"家","kanji":"家","reading":"いえ","meaning":"じぶんが すんで いる ところ","englishTerm":"home","englishMeaning":"the place where you live"},
  {"term":"一日","kanji":"一日","reading":"いちにち","meaning":"あさから よるまで。24時間の こと","englishTerm":"one day","englishMeaning":"from morning until night"},
  {"term":"本当","kanji":"本当","reading":"ほんとう","meaning":"うそでは ない こと。じっさいに あった こと","englishTerm":"real, true","englishMeaning":"not a lie; something that really happened"},
  {"term":"早め","kanji":"早め","reading":"はやめ","meaning":"きめた 時間より 前に する こと","englishTerm":"a little early","englishMeaning":"doing it before the time you were given"},
  {"term":"質問","kanji":"質問","reading":"しつもん","meaning":"わからない ことを、人に たずねる こと","englishTerm":"question","englishMeaning":"asking someone about something you do not know"},
  {"term":"元気","kanji":"元気","reading":"げんき","meaning":"体や 気持ちに 力が ある こと","englishTerm":"energy, cheerful","englishMeaning":"feeling strong and well in body and mind"},
  {"term":"やり方","kanji":"やり方","reading":"やりかた","meaning":"どう すれば できるか、という こと","englishTerm":"way of doing","englishMeaning":"the steps and style you use to do something"},
  {"term":"アプリ","kanji":null,"reading":"あぷり","meaning":"スマホや パソコンの 中で うごく もの。ちずや ゲームなど","englishTerm":"app","englishMeaning":"a program you use on a phone or computer"},
  {"term":"アイデア","kanji":null,"reading":"あいであ","meaning":"「こう したら いいかも」と 思いついた 考え","englishTerm":"idea","englishMeaning":"a new thought about what you could do"},
  {"term":"大事","kanji":"大事","reading":"だいじ","meaning":"important の ことばです。","englishTerm":"important","englishMeaning":"something that matters a lot to you"},
  {"term":"順番","kanji":"順番","reading":"じゅんばん","meaning":"どれを 先に、どれを 後に するかの ならび方です。","englishTerm":"order / sequence","englishMeaning":"which one comes first and which comes next"},
  {"term":"記録","kanji":"記録","reading":"きろく","meaning":"後で 見られるように、書いて 残す ことです。","englishTerm":"a record","englishMeaning":"writing something down so you can look at it later"},
  {"term":"準備","kanji":"準備","reading":"じゅんび","meaning":"始める 前に、いる ものを そろえる ことです。","englishTerm":"preparation","englishMeaning":"getting ready before you start"},
  {"term":"案内","kanji":"案内","reading":"あんない","meaning":"行き方や やり方を、その 人に 見せる ことです。","englishTerm":"guiding someone","englishMeaning":"showing someone the way or how to do it"},
  {"term":"発表","kanji":"発表","reading":"はっぴょう","meaning":"みんなの 前で、調べた ことや 考えを 話す ことです。","englishTerm":"a presentation","englishMeaning":"telling a group what you found or thought"},
  {"term":"違い","kanji":"違い","reading":"ちがい","meaning":"2つを くらべた とき、同じでは ない ところです。","englishTerm":"a difference","englishMeaning":"the part where two things are not the same"},
  {"term":"必ず","kanji":"必ず","reading":"かならず","meaning":"ぜったいに そう する、という ことです。","englishTerm":"always","englishMeaning":"for sure, every time, with no exception"},
  {"term":"静か","kanji":"静か","reading":"しずか","meaning":"音が 小さい ようすです。","englishTerm":"quiet","englishMeaning":"with little or no sound"},
  {"term":"速い","kanji":"速い","reading":"はやい","meaning":"進む スピードが 大きい ことです。","englishTerm":"fast","englishMeaning":"moving or working at high speed"},
  {"term":"変わる","kanji":"変わる","reading":"かわる","meaning":"前と 同じでは なく なる ことです。","englishTerm":"to change","englishMeaning":"to become different from before"},
  {"term":"助けます","kanji":"助けます","reading":"たすけます","meaning":"困って いる 人に 力を かす ことです。","englishTerm":"to help","englishMeaning":"to give your strength to someone in trouble"},
  {"term":"支えます","kanji":"支えます","reading":"ささえます","meaning":"下から 力を 出して、たおれないように する ことです。","englishTerm":"to support","englishMeaning":"to hold something up so it does not fall"},
  {"term":"任せて","kanji":"任せて","reading":"まかせて","meaning":"その 人に やって もらうように する ことです。","englishTerm":"to entrust","englishMeaning":"to let another person do the work and trust them"},
  {"term":"頼まれた","kanji":"頼まれた","reading":"たのまれた","meaning":"人から「やって ください」と 言われた ことです。","englishTerm":"asked to do","englishMeaning":"when someone has asked you to do something"},
  {"term":"困って","kanji":"困って","reading":"こまって","meaning":"どう すれば いいか わからない ようすです。","englishTerm":"in trouble","englishMeaning":"not knowing what to do and needing help"},
  {"term":"覚えます","kanji":"覚えます","reading":"おぼえます","meaning":"見た ことや 聞いた ことを、頭に 入れる ことです。","englishTerm":"to learn / remember","englishMeaning":"to put what you saw or heard into your head"},
  {"term":"探します","kanji":"探します","reading":"さがします","meaning":"見つけるために、あちこちを 見る ことです。","englishTerm":"to look for","englishMeaning":"to try to find something"},
  {"term":"誘います","kanji":"誘います","reading":"さそいます","meaning":"「いっしょに やりませんか」と 声を かける ことです。","englishTerm":"to invite","englishMeaning":"to ask someone to join you"},
  {"term":"直します","kanji":"直します","reading":"なおします","meaning":"壊れた ものを 元に もどす ことです。","englishTerm":"to fix","englishMeaning":"to make a broken thing work again"},
  {"term":"壊れた","kanji":"壊れた","reading":"こわれた","meaning":"うまく 動かなく なった ようすです。","englishTerm":"broken","englishMeaning":"no longer working the way it should"},
  {"term":"止まった","kanji":"止まった","reading":"とまった","meaning":"動いて いた ものが、動かなく なった ことです。","englishTerm":"stopped","englishMeaning":"something that was moving is not moving now"},
  {"term":"始めます","kanji":"始めます","reading":"はじめます","meaning":"まだ やって いない ことを、これから やる ことです。","englishTerm":"to start","englishMeaning":"to begin doing something new"},
  {"term":"落ち着いて","kanji":"落ち着いて","reading":"おちついて","meaning":"急がないで、気持ちを 静かに して いる ようすです。","englishTerm":"calmly","englishMeaning":"without hurrying or panicking"},
];
